mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

polls/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('po/', views.po_list, name='po_list'),
    path('po/<int:po_id>/', views.po_view, name='po_view'),
    path('po/<int:po_id>/create_shippment', views.shippment_from_po, name='shippment_from_po'),
    path('po/shippments', views.shippment_list, name='shippment_list'),
    path('parts/', views.part_list, name='part_list'),
    path('parts/add', views.part_add, name='part_add'),
    path('vendors/', views.vendor_list, name='vendor_list'),
    path('vendors/add', views.vendor_add, name='vendor_add'),
]

polls/models.py
from django.db import models

# Part/Vendor are used for drop down list and not data
# Other models are physical stuff that constantly gets added

class Vendor(models.Model):
    vendor_name = models.CharField(max_length=32)
    vendor_id = models.CharField(max_length=32)
    address = models.CharField(max_length=256)

    def __str__(self):
        return self.vendor_name

class PO(models.Model):
    po_number = models.CharField(max_length=16)
    vendor = models.ForeignKey(Vendor, models.DO_NOTHING, null=True)
    date = models.DateField()
    notes = models.CharField(max_length=256)

    def __str__(self):
        return self.po_number

class Part(models.Model): 
    number = models.CharField(max_length=32)
    name = models.CharField(max_length=32)
    vendor = models.ForeignKey(Vendor, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name

class Shippment(models.Model):
    po = models.ForeignKey(PO, on_delete=models.CASCADE)
    date_shipped = models.DateField()
    date_received = models.DateField()
    shipped_from = models.CharField(max_length=16)
    shipped_to = models.CharField(max_length=16)
    shipper_receiver_id = models.CharField(max_length=16)
    description = models.CharField(max_length=128, null=True)
    manager = models.CharField(max_length=64)
    notes = models.CharField(max_length=256, null=True)
    due_date = models.DateField(null=True)

    def __str__(self):
        return 'ID: ' + self.shipper_receiver_id + ' || DATE: ' + str(self.date_received) + ' || PO: ' + self.po.po_number

class OrderedPart(models.Model):
    initialized = False
    po = models.ForeignKey(PO, on_delete=models.CASCADE)
    vendor = models.ForeignKey(Vendor, on_delete=models.DO_NOTHING, null=True)
    part = models.ForeignKey(Part, on_delete=models.DO_NOTHING, null=True)
    shippment = models.ManyToManyField(
        Shippment, 
        auto_created=False, 
        blank=True, 
        null=True
        )
    is_shipped = models.BooleanField(default=False)
    quantity_received = models.IntegerField(default=0)
    quantity_expected = models.IntegerField()

    def __str__(self):
        return self.part.name + ' || ' + self.part.number + ' || PO: ' + self.po.po_number

polls/forms.py
from django import forms
from django.db import models
from django import forms
from django.db.models import fields

from .models import PO, OrderedPart, Shippment, Part, Vendor
from .widget import DatePickerInput

class POShippmentForm(forms.Form):

    def __init__(self, *args, **kwargs):
        self.selected_po = kwargs.pop('selected_po')
        self.po_parts = self.selected_po.orderedpart_set.filter(is_shipped=False)
        super().__init__(*args, **kwargs)
        for ordered_part in self.po_parts:
            print('this ran')
            self.fields['quantity_received_%s' % ordered_part.part.name] = forms.IntegerField(initial=0)
            self.fields['is_received_%s' % ordered_part.part.name] = forms.BooleanField(required=False)

    date_shipped = forms.DateField(widget=DatePickerInput)
    date_received = forms.DateField(widget=DatePickerInput)
    shipped_from = forms.CharField(max_length=16)
    shipped_to = forms.CharField(max_length=16)
    shipper_receiver_id = forms.CharField(max_length=16)
    description = forms.CharField(max_length=128, required=False)
    manager = forms.CharField(max_length=64)
    notes = forms.CharField(max_length=256, required=False)
    due_date = forms.DateField(widget=DatePickerInput, required=False)

class PartForm(forms.ModelForm):
    class Meta:
        model = Part
        fields = ['number', 'name', 'vendor']

class VendorForm(forms.ModelForm):
    class Meta:
        model = Vendor
        fields = ['vendor_name', 'vendor_id', 'address']

polls/views.py
from django.db.models import manager
from django.http.response import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.urls import reverse
from django.http import JsonResponse
import datetime
from django.utils import timezone

from .models import PO, Part, Shippment, Vendor
from .forms import POShippmentForm, PartForm, VendorForm

def index(request):
    return render(request, 'polls/index.html')

def po_list(request):
    object_list = PO.objects.all()
    return render(request, 'polls/po_list.html', {'object_list': object_list})

def po_view(request, po_id):
    po = PO.objects.get(po_number=po_id)
    return render(request, 'polls/po_view.html', {'po': po})

def part_list(request):
    part_list = Part.objects.all()
    context= {
        'part_list': part_list,
    }
    return render(request, 'polls/part_list.html', context)

def part_add(request):
    if request.method == 'POST':
        form = PartForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('polls:part_list'))

    form = PartForm()
    context = {
        'form': form,
    }
    return render(request, 'polls/part_add.html', context)

def vendor_list(request):
    vendor_list = Vendor.objects.all()
    context = {
        'vendor_list': vendor_list,
    }
    return render(request, 'polls/vendor_list.html', context)

def vendor_add(request):
    if request.method == 'POST':
        form = VendorForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('polls:vendor_list'))

    form = VendorForm()
    context = {
        'form': form,
    }
    return render(request, 'polls/vendor_add.html', context)

def shippment_list(request):
    shippment_list = Shippment.objects.all()
    context = {
        'shippment_list': shippment_list
    }
    return render(request, 'polls/shippment_list.html', context)

def shippment_from_po(request, po_id):
    this_po = PO.objects.get(po_number=po_id)
    if request.method == 'POST':
        form = POShippmentForm(request.POST, selected_po=this_po)
        if form.is_valid():
            s = Shippment(
                po=this_po,
                date_shipped = form.cleaned_data['date_shipped'],
                date_received = form.cleaned_data['date_received'],
                shipped_from = form.cleaned_data['shipped_from'],
                shipped_to = form.cleaned_data['shipped_to'],
                shipper_receiver_id = form.cleaned_data['shipper_receiver_id'],
                description = form.cleaned_data['description'],
                manager = form.cleaned_data['manager'],
                notes = form.cleaned_data['notes'],
                due_date = form.cleaned_data['due_date'],
                )
            s.save()

            for ordered_part in form.po_parts:
                print(form.cleaned_data['is_received_%s' % ordered_part.part.name])
                if form.cleaned_data['is_received_%s' % ordered_part.part.name] == True:
                    ordered_part.is_shipped = True
                    ordered_part.shippment = s
                    ordered_part.save()
                if form.cleaned_data['quantity_received_%s' % ordered_part.part.name] > 0:
                    temp = form.cleaned_data['quantity_received_%s' % ordered_part.part.name]
                    ordered_part.quantity_received = ordered_part.quantity_received + temp
                    ordered_part.shippment.add(s)
                    ordered_part.save()
            
            return HttpResponseRedirect(reverse('polls:index'))

    form = POShippmentForm(selected_po=this_po)
    context = {
        'po_id': po_id,
        'po': this_po,
        'form': form,
    }
    return render(request, 'polls/shippment_from_po.html', context)

polls/templates/polls/generic_list.html
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>

{% if data %}
    <h2>{{ title }} - <a href="{% url 'polls:index' %}">(Go back)</a></h2>

    <table>
        <ul>
            <tr>
                {% for field, value in data.0.fields.items %}
                    <th>{{ field }}</th>
                {% endfor %}
            </tr>
        </ul>

        <ul>
        {% for object in data %}
            <tr>
                <ul>
                    {% for field, value in object.fields.items %}
                        <td>{{ value }}</td>
                    {% endfor %}
                </ul>
            </tr>
        {% endfor %}
        </ul>

    </table>
{% else %}
    <p>No polls are available.</p>
{% endif %}

</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'polls:po_list' %}">Open POs</a> <br>
    <a href="{% url 'polls:shippment_list' %}">Shippments</a> <br>
    Ordered Parts <br>
    ------------- <br>
    Create PO <br>
    Create Shippment <br> 
    ------------- <br>
    <a href="{% url 'polls:part_add' %}">Add to parts list</a> <br>
    <a href="{% url 'polls:vendor_add' %}">Add to vendor list</a> <br>
    ------------- <br>
    <a href="{% url 'polls:part_list' %}">View parts list</a> <br>
    <a href="{% url 'polls:vendor_list' %}">View vendor list</a> <br>
</body>
</html>

polls/templates/polls/part_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method ="post">
        {% csrf_token %}
        <a href="{% url 'polls:part_list' %}">(Go Back)</a> <br> <br>
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">Submit</button>
    </form>
</body>
</html>

polls/templates/polls/part_list.html
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>

{% if part_list %}
    <h2>All Known Parts - <a href="{% url 'polls:index' %}">(Go back)</a> - 
    <a href="{% url 'polls:part_add' %}">(Add Part)</a>
    </h2>

    <table>
        <tr>
            <th>Number</th>
            <th>Name</th>
            <th>Vendor</th>
        </tr>

        <ul>
        {% for part in part_list reversed %}
            <tr>
               <td>{{part.number}}</td>
               <td>{{part.name}}</td>
               <td>{{part.vendor.vendor_name}}</td>
            </tr>
        {% endfor %}
        </ul>

    </table>
{% else %}
    <p>No polls are available.</p>
{% endif %}

</body>
</html>

polls/templates/polls/po_list.html
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>

{% if object_list %}
    <h2>Open POs (Click for details) - <a href="{% url 'polls:index' %}">(Go back)</a></h2>

    <table>
        <tr>
            <th>PO Number</th>
            <th>Vendor</th>
        </tr>

        <ul>
        {% for object in object_list reversed %}
            <tr>
                <td>{{ object.po_number }} - <a href="{% url 'polls:po_view' object.po_number %}">(View Details)</a> </td>
                <td>{{ object.vendor }}</td>
            </tr>
        {% endfor %}
        </ul>

    </table>
{% else %}
    <p>No POs are available.</p>
{% endif %}

</body>
</html>

polls/templates/polls/po_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    PO NUMBER: {{ po.po_number }} <a href="{% url 'polls:po_list' %}">(Go Back)</a> <br> <br>
    VENDOR: {{ po.vendor }} <br> <br>
    PO DATE: {{ po.date }} <br> <br>
    Notes: {{ po.notes }} <br> <br>
    {% for part in po.orderedpart_set.all %}
        ({{ part.part.number }} - {{ part.part.name }}) 
        || Received: {{ part.quantity_received }}/{{ part.quantity_expected }} 
        || Finished: {{ part.is_shipped }} <br> <br>
    {% endfor %}
    <a href="{% url 'polls:shippment_from_po' po_id=po.po_number %}">Create shippment from po!</a> <br>
</body>
</html>

polls/templates/polls/shippment_from_po.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method ="post">
        {% csrf_token %}
        <a href="{% url 'polls:po_view' po_id %}">(Go Back)</a> <br> <br>
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">Submit</button>
    </form>
</body>
</html>

polls/templates/polls/shippment_list.html
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>

{% if shippment_list %}
    <h2>All Shippments - <a href="{% url 'polls:index' %}">(Go back)</a></h2>

    <table>
        <ul>
            <tr>
                <th>PO</th>
                <th>Ordered Parts</th>
                <th>Quantity Received</th>
                <th>Quantity Expected</th>
                <th>Date Shipped</th>
                <th>Date Received</th>
                <th>Shipped From</th>
                <th>Shipped To</th>
                <th>Shipper Receiver ID</th>
                <th>Description</th>
                <th>Manager</th>
                <th>Notes</th>
                <th>Due Date</th>
            </tr>
        </ul>

        <ul>
        {% for shippment in shippment_list %}
            <tr>
                <ul>
                    <td><a href="{% url 'polls:po_view' shippment.po.po_number %}">{{ shippment.po.po_number }}</a></td>
                    <td>{% for part in shippment.orderedpart_set.all %}
                            {% if part.is_shipped %}
                                <l style="color:green;">{{ part.part.number }}, </style>
                            {% else %}
                                <l style="color:red;">{{ part.part.number }}, </style>
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        {% for part in shippment.orderedpart_set.all %}
                            {% if part.is_shipped %}
                                <l style="color:green;">{{ part.quantity_received }}, </style>
                            {% else %}
                                <l style="color:red;">{{ part.quantity_received }}, </style>
                            {% endif %} 
                        {% endfor %}
                    </td>
                    <td>
                        {% for part in shippment.orderedpart_set.all %}
                            {% if part.is_shipped %}
                                <l style="color:green;">{{ part.quantity_expected }}, </style>
                            {% else %}
                                <l style="color:red;">{{ part.quantity_expected }}, </style>
                            {% endif %} 
                        {% endfor %}
                    </td>
                    <td>{{ shippment.date_shipped }}</td>
                    <td>{{ shippment.date_received }}</td>
                    <td>{{ shippment.shipped_from }}</td>
                    <td>{{ shippment.shipped_to }}</td>
                    <td>{{ shippment.shipper_receiver_id }}</td>
                    <td>{{ shippment.description }}</td>
                    <td>{{ shippment.manager }}</td>
                    <td>{{ shippment.notes }}</td>
                    <td>{{ shippment.due_date }}</td>
                </ul>
            </tr>
        {% endfor %}
        </ul>

    </table>
{% else %}
    <p>No polls are available.</p>
{% endif %}

</body>
</html>

polls/templates/polls/vendor_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method ="post">
        {% csrf_token %}
        <a href="{% url 'polls:vendor_list' %}">(Go Back)</a> <br> <br>
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">Submit</button>
    </form>
</body>
</html>

polls/templates/polls/vendor_list.html
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>

{% if vendor_list %}
    <h2>All Known Vendors - <a href="{% url 'polls:index' %}">(Go back)</a> - 
      <a href="{% url 'polls:vendor_add' %}">(Add Vendor)</a>
    </h2>

    <table>
        <tr>
            <th>Name</th>
            <th>ID</th>
            <th>Address</th>
        </tr>

        <ul>
        {% for vendor in vendor_list reversed %}
            <tr>
               <td>{{vendor.vendor_name}}</td>
               <td>{{vendor.vendor_id}}</td>
               <td>{{vendor.address}}</td>
            </tr>
        {% endfor %}
        </ul>

    </table>
{% else %}
    <p>No polls are available.</p>
{% endif %}

</body>
</html>